#!/usr/bin/env python3
"""Build CT prelim TOPAS spots + run decks from the optimized plan files.

Outputs under ct/topas/mc_ref/:
  spots_single.txt      highest-weight 235 MeV/u spot, 50k histories
  spots_layer_eq.txt    20 highest-weight 220 MeV/u spots, equal 5k each
  run_single_spot.txt   DoseToMedium on Patient (417×505×35) CSV
  run_layer_eq.txt

Also writes a rebin helper for TOPAS CSV → compare grid (104×126×35 @ 2 mm).
"""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path


def parse_channels(path: Path) -> dict[int, list[float]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    channels: dict[int, list[float]] = {}
    for line in lines:
        m = re.match(
            r"[diu]v:Tf/Scatterer1/L(\d+)/Values\s*=\s*(.*)", line.strip()
        )
        if not m:
            continue
        lab = int(m.group(1))
        body = re.sub(r"\b(MeV|mm|deg|ms)\b", "", m.group(2))
        parts = body.split()
        n = int(float(parts[0]))
        channels[lab] = [float(x) for x in parts[1 : n + 1]]
    if 0 not in channels:
        raise SystemExit(f"No L0 Values in {path}")
    return channels


def load_combined(spots_paths: list[Path]) -> dict[int, list[float]]:
    combined: dict[int, list[float]] = {}
    for path in spots_paths:
        ch = parse_channels(path)
        for lab, vals in ch.items():
            combined.setdefault(lab, []).extend(vals)
    n = len(combined[0])
    for lab, vals in combined.items():
        if len(vals) != n:
            raise SystemExit(f"Channel L{lab} length {len(vals)} != {n}")
    return combined


def write_spots(
    out: Path,
    channels: dict[int, list[float]],
    indices: list[int],
    histories: list[int],
) -> None:
    n = len(indices)
    out.parent.mkdir(parents=True, exist_ok=True)
    type_for = {
        0: "iv",
        1: "dv",
        2: "dv",
        3: "uv",
        4: "iv",
        5: "dv",
        6: "dv",
        7: "dv",
        8: "dv",
        9: "dv",
        10: "uv",
        11: "uv",
        12: "dv",
        13: "uv",
        14: "uv",
    }
    units = {
        1: " MeV",
        2: " MeV",
        5: " mm",
        6: " mm",
        7: " deg",
        8: " deg",
        9: " mm",
        12: " mm",
    }
    lines: list[str] = []
    for lab in range(15):
        lines.append(f's:Tf/Scatterer1/L{lab}/Function = "Step"')
    lines.append("")
    times = " ".join(str(float(i + 1)) for i in range(n))
    lines.append(f"dv:Tf/Scatterer1/L0/Times = {n} {times} ms")
    for lab in range(1, 15):
        lines.append(f"dv:Tf/Scatterer1/L{lab}/Times   = Tf/Scatterer1/L0/Times ms")
    lines.append("")
    for lab in range(15):
        typ = type_for[lab]
        if lab == 0:
            vals = [float(i + 1) for i in range(n)]
        elif lab == 4:
            vals = [float(h) for h in histories]
        else:
            vals = [channels[lab][i] for i in indices]
        if lab in (0, 4):
            body = " ".join(str(int(v)) for v in vals)
        else:
            body = " ".join(f"{v:.6g}" for v in vals)
        unit = units.get(lab, "")
        lines.append(f"{typ}:Tf/Scatterer1/L{lab}/Values = {n} {body}{unit}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({n} spots, histories={histories[0] if len(set(histories))==1 else 'mixed'})")


def write_run(
    out: Path,
    spots_name: str,
    timeline_end_ms: float,
    n_times: int,
    tag: str,
    threads: int,
    dicom_directory: str,
) -> None:
    # Geometry from production run_c_01.txt (patient plan RotZ=+90).
    # DoseToMedium on Patient at native DICOM bins; CSV for compare pipeline.
    text = f"""# CT prelim TOPAS MC — {tag}
# Auto-generated by prepare_ct_prelim_topas.py
i:Ts/Seed = 20260721
i:Ts/NumberOfThreads = {threads}
b:Ts/ShowHistoryCountLessFrequentlyAsSimulationProgresses = "True"
b:Gr/Enable = "False"
b:Ge/CheckForOverlaps = "False"
b:Ge/QuitIfOverlapDetected = "False"

s:Ge/World/Type = "TsBox"
s:Ge/World/Material = "Air"
d:Ge/World/HLX = 2.0 m
d:Ge/World/HLY = 2.0 m
d:Ge/World/HLZ = 2.0 m

s:Ge/Patient/Type = "TsDicomPatient"
s:Ge/Patient/Parent = "World"
d:Ge/Patient/TransX = -42.8515 mm
d:Ge/Patient/TransY = -12.7636 mm
d:Ge/Patient/TransZ = 1.3617 mm
d:Ge/Patient/RotX = 0. deg
d:Ge/Patient/RotY = 0. deg
d:Ge/Patient/RotZ = 90.0000 deg
s:Ge/Patient/DicomDirectory = "{dicom_directory}"
sv:Ge/Patient/DicomModalityTags = 1 "CT"
includeFile = HUtoMaterialSchneider.txt
b:Ge/Patient/PreLoadAllMaterials = "True"
i:Gr/ShowOnlyOutlineIfVoxelCountExceeds = 1

# DoseToMedium on full patient grid (native DICOM). Rebin offline to 104×126×35.
s:Sc/PrelimDose/Quantity = "DoseToMedium"
s:Sc/PrelimDose/Component = "Patient"
i:Sc/PrelimDose/XBins = 417
i:Sc/PrelimDose/YBins = 505
i:Sc/PrelimDose/ZBins = 35
s:Sc/PrelimDose/OutputType = "csv"
s:Sc/PrelimDose/OutputFile = "output/prelim_{tag}_dose"
s:Sc/PrelimDose/IfOutputFileAlreadyExists = "Overwrite"
b:Sc/PrelimDose/OutputAfterRun = "True"
sv:Sc/PrelimDose/Report = 1 "Sum"

includeFile = {spots_name}

sv:Ph/Default/Modules = 7 "g4em-standard_opt4" "g4h-phy_QGSP_BIC_HP" "g4decay" "g4ion-inclxx" "g4h-elastic_HP" "g4stopping" "g4radioactivedecay"

d:Tf/TimelineEnd = {timeline_end_ms:.1f} ms
i:Tf/NumberOfSequentialTimes = {n_times}

s:Ge/BeamPosition2/Parent = "World"
s:Ge/BeamPosition2/Type = "Group"
d:Ge/BeamPosition2/TransX = Tf/Scatterer1/L5/Value mm
d:Ge/BeamPosition2/TransY = -0.45 m
d:Ge/BeamPosition2/TransZ = Tf/Scatterer1/L6/Value mm
d:Ge/BeamPosition2/RotX = Tf/Scatterer1/L7/Value deg
d:Ge/BeamPosition2/RotY = Tf/Scatterer1/L8/Value deg
d:Ge/BeamPosition2/RotZ = 0. deg

s:Ge/BeamPosition20/Parent = "BeamPosition2"
s:Ge/BeamPosition20/Type = "TsBox"
s:Ge/BeamPosition20/Material = "Air"
d:Ge/BeamPosition20/HLX = 1 cm
d:Ge/BeamPosition20/HLY = 1 cm
d:Ge/BeamPosition20/HLZ = 2 cm
d:Ge/BeamPosition20/TransX = 0. m
d:Ge/BeamPosition20/TransY = 0. m
d:Ge/BeamPosition20/TransZ = 0. m

s:So/CarbonSource/Type = "emittance"
s:So/CarbonSource/Component = "BeamPosition2"
s:So/CarbonSource/BeamParticle = "GenericIon(6,12,6)"
s:So/CarbonSource/Distribution = "BiGaussian"
d:So/CarbonSource/BeamEnergy = Tf/Scatterer1/L2/Value MeV
u:So/CarbonSource/BeamEnergySpread = Tf/Scatterer1/L3/Value
d:So/CarbonSource/SigmaX = Tf/Scatterer1/L9/Value mm
u:So/CarbonSource/SigmaXprime = Tf/Scatterer1/L10/Value
u:So/CarbonSource/CorrelationX = Tf/Scatterer1/L11/Value
d:So/CarbonSource/SigmaY = Tf/Scatterer1/L12/Value mm
u:So/CarbonSource/SigmaYprime = Tf/Scatterer1/L13/Value
u:So/CarbonSource/CorrelationY = Tf/Scatterer1/L14/Value
i:So/CarbonSource/NumberOfHistoriesInRun = Tf/Scatterer1/L4/Value
i:Ts/ShowHistoryCountAtInterval = 2000
"""
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--spots",
        nargs="+",
        type=Path,
        default=[Path("ct/topas/spots_c_01.txt"), Path("ct/topas/spots_c_02.txt")],
    )
    ap.add_argument("--weights", type=Path, default=Path("ct/spotWeight.csv"))
    ap.add_argument("--outdir", type=Path, default=Path("ct/topas/mc_ref"))
    ap.add_argument("--single-histories", type=int, default=50000)
    ap.add_argument("--layer-spots", type=int, default=20)
    ap.add_argument("--layer-histories-each", type=int, default=5000)
    ap.add_argument("--threads", type=int, default=40)
    ap.add_argument("--dicom-directory", default="../../dicom")
    args = ap.parse_args()

    ch = load_combined(args.spots)
    n = len(ch[0])
    weights = []
    with args.weights.open(encoding="utf-8-sig") as handle:
        for row in csv.reader(handle):
            if not row:
                continue
            weights.append(float(row[0]))
    if len(weights) != n:
        raise SystemExit(f"weights {len(weights)} != spots {n}")

    energies_MeVu = [e / 12.0 for e in ch[2]]
    # Highest-weight 235 MeV/u spot
    idx_235 = [i for i in range(n) if abs(energies_MeVu[i] - 235.0) < 0.1]
    if not idx_235:
        raise SystemExit("No 235 MeV/u spots found")
    single = max(idx_235, key=lambda i: weights[i])
    print(
        f"single spot index={single} weight={weights[single]:.4g} "
        f"E={energies_MeVu[single]:.1f} MeV/u tx={ch[5][single]:.4g} tz={ch[6][single]:.4g}"
    )

    idx_220 = [i for i in range(n) if abs(energies_MeVu[i] - 220.0) < 0.1]
    if len(idx_220) < args.layer_spots:
        raise SystemExit(f"Only {len(idx_220)} spots at 220 MeV/u")
    layer = sorted(idx_220, key=lambda i: -weights[i])[: args.layer_spots]
    print(f"layer_eq {len(layer)} spots at 220 MeV/u, top weight={weights[layer[0]]:.4g}")

    out = args.outdir
    write_spots(
        out / "spots_single.txt",
        ch,
        [single],
        [args.single_histories],
    )
    write_spots(
        out / "spots_layer_eq.txt",
        ch,
        layer,
        [args.layer_histories_each] * len(layer),
    )
    write_run(
        out / "run_single_spot.txt",
        "spots_single.txt",
        timeline_end_ms=1.0,
        n_times=1,
        tag="single",
        threads=args.threads,
        dicom_directory=args.dicom_directory,
    )
    write_run(
        out / "run_layer_eq.txt",
        "spots_layer_eq.txt",
        timeline_end_ms=float(len(layer)),
        n_times=len(layer),
        tag="layer_eq",
        threads=args.threads,
        dicom_directory=args.dicom_directory,
    )

    # GPU-side spot files (same content) for prelim configs already point here.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
