#!/usr/bin/env python3
"""Generate the development-only C-12/water stopping-power table.

This transparent approximation exists to exercise the software. Replace its
output with a traceable ICRU/Geant4-derived dataset before physics validation.
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path


K_MEV_CM2_PER_G = 0.307075
ELECTRON_MASS_MEV = 0.51099895
NUCLEON_MASS_MEV = 931.49410242
WATER_Z_OVER_A = 0.55509
WATER_MEAN_EXCITATION_MEV = 75.0e-6
CARBON_Z = 6.0


def stopping_power_mev_per_mm(energy_mevu: float) -> float:
    gamma = 1.0 + energy_mevu / NUCLEON_MASS_MEV
    beta_squared = 1.0 - 1.0 / (gamma * gamma)
    beta = math.sqrt(beta_squared)
    effective_charge = CARBON_Z * (
        1.0 - math.exp(-125.0 * beta * CARBON_Z ** (-2.0 / 3.0))
    )
    logarithm_argument = (
        2.0
        * ELECTRON_MASS_MEV
        * beta_squared
        * gamma
        * gamma
        / WATER_MEAN_EXCITATION_MEV
    )
    bracket = math.log(logarithm_argument) - beta_squared
    mass_stopping = (
        K_MEV_CM2_PER_G
        * effective_charge
        * effective_charge
        * WATER_Z_OVER_A
        * bracket
        / beta_squared
    )
    # At 1 g/cm3: MeV cm2/g -> MeV/cm, then convert cm -> mm.
    return mass_stopping / 10.0


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("data/stopping_power_water.csv"))
    parser.add_argument("--maximum-energy", type=int, default=400)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", newline="", encoding="utf-8") as stream:
        stream.write("# DEVELOPMENT-ONLY TABLE; not an ICRU/Geant4 reference dataset.\n")
        stream.write("# Generated by tools/generate_stopping_power.py using the documented\n")
        stream.write("# Bethe-Bloch + Hubert-style effective-charge approximation for C-12 in water.\n")
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow(["energy_MeVu", "stopping_power_MeV_per_mm"])
        for energy in range(1, args.maximum_energy + 1):
            writer.writerow([f"{energy:.1f}", f"{stopping_power_mev_per_mm(energy):.8f}"])


if __name__ == "__main__":
    main()

