% build_bio_dij_osmk_sparse.m
% Build sparse-double OSMK biological dose influence matrices from the
% direct TOPAS OSMK scorers generated by generate_topas_files.m.
%
% Expected TOPAS scorer names:
%   OSMK_Dtotal_*_%02d_Run_%04d.bin   -> DoseToMedium, total denominator
%   OSMK_Ad_*_%02d_Run_%04d.bin       -> sum D_ion * z_d
%   OSMK_AdStar_*_%02d_Run_%04d.bin   -> sum D_ion * z_d*
%   OSMK_AnStar_*_%02d_Run_%04d.bin   -> sum D_ion * z_n*
%
% Old unlabelled CSV names are still accepted as a fallback.
%
% Current case scripts use TsDicomPatient and attach the OSMK scorers to
% Component = "Patient". TOPAS therefore writes scorer values in the
% patient-local CT grid. Import only needs TOPAS [X Y Z] -> matRad [Y X Z]
% reindexing; no gantry-180 flip/shift is applied here.
%
% This script keeps the native TOPAS/DICOM CT grid and saves sparse double
% matrices. Values with abs(value) below the thresholds are dropped before
% sparse insertion.

clear; clc;

%% Threshold parameters
% Tune these four values to trade accuracy for storage size.
% zd_limit = 0;
% zdstar_limit = 0;
% zn_limit = 0;
% dose_limit = 0;

zd_limit     = 4e-4;
zdstar_limit = 7e-5;
zn_limit     = 6e-7;
% The previous 2e-6 cutoff removed 87.3% of nonzero Dtotal entries in the
% RT07575 C-12 Dij.  With sum(resultGUI.w)=43165.5, its per-voxel accumulated
% omission bound was 0.0863 Gy, essentially the full 3%-of-peak gamma dose
% tolerance.  Keep the physical-dose cutoff one order lower; use zero for a
% storage-heavy reference build.  The raw/dropped sums saved below make the
% remaining integral loss directly auditable after every build.
dose_limit   = 2e-7;

%% Configuration
project_dir = fileparts(mfilename('fullpath'));

% Build one ion at a time. Current generated TOPAS folders are scripts_c
% and scripts_ne, with scorer names such as OSMK_Dtotal_c_01_Run_0000.bin.
ion_label = 'c';  % 'c' or 'ne'
output_file = fullfile(project_dir, sprintf('bio_dij_osmk_sparse_%s.mat', ion_label));

% Optional final optimizer result used only for a conservative audit.  The
% Dij build does not depend on these weights.  When present, the script
% reports the largest plan-dose omission that the configured Dtotal cutoff
% could produce: dose_limit * sum(abs(w)).
optimizer_result_file = fullfile(project_dir, 'code_v2', ...
    sprintf('RBE_dose_result_%s.mat', ion_label));

scorer_dir_candidates = {
    fullfile(project_dir, ['scripts_' ion_label])
    project_dir
    };

[topas_dims, resolution_mm, dicom_crop_info] = getCurrentTopasGrid(project_dir);
dim_matRad = [topas_dims(2), topas_dims(1), topas_dims(3)];

spots_dir = fullfile(project_dir, ['scripts_' ion_label]);
topas_spot_groups = readTopasSpotGroupsFromSpotsFiles(spots_dir, ion_label);
num_topas_chunks = numel(topas_spot_groups);
num_spots = max(cellfun(@max, topas_spot_groups));
all_spot_ids = sort(vertcat(topas_spot_groups{:}));
if ~isequal(all_spot_ids(:), (1:num_spots)')
    error('Spot IDs parsed from %s are not contiguous 1..%d.', spots_dir, num_spots);
end

% Build small DIJ blocks first, then merge once. Repeatedly inserting new
% columns into one growing sparse matrix becomes increasingly slow.
max_spots_per_dij_chunk = 100;
[work_topas_chunks, work_run_ids, work_spot_ids] = makeSpotWorkItems(topas_spot_groups);
num_dij_chunks = ceil(numel(work_spot_ids) / max_spots_per_dij_chunk);

% TOPAS scorer files for this CT grid are large. Keep serial by default to
% avoid reading several ~hundred-MB per-spot binary files at once.
num_workers = 4;
use_parallel = defaultUseParallel();
topas_spot_grouping = 'spotsFilesGlobalIds';

% A missing scorer must never become a silent all-zero Dij column in a final
% clinical-plan build.  Temporarily set false only when deliberately
% inspecting a partial transfer; such an output is not valid for planning.
fail_on_missing = true;

scorer_names = {'OSMK_Dtotal', 'OSMK_Ad', 'OSMK_AdStar', 'OSMK_AnStar'};
preferred_scorer_extension = '.bin';
scorer_limits = [dose_limit, zd_limit, zdstar_limit, zn_limit];
if any(scorer_limits < 0)
    error('Threshold parameters must be nonnegative.');
end

%% Resolve inputs
num_voxels = prod(dim_matRad);
if num_voxels ~= prod(topas_dims)
    error('Dimension mismatch: matRad voxels=%d, TOPAS voxels=%d.', ...
        num_voxels, prod(topas_dims));
end

fprintf('>>> Ion label: %s\n', ion_label);
fprintf('>>> Spots parsed from TOPAS spots files: %d across %d TOPAS chunks\n', num_spots, num_topas_chunks);
fprintf('>>> DIJ build chunk size: <= %d spots (%d DIJ chunks)\n', ...
    max_spots_per_dij_chunk, num_dij_chunks);
fprintf('>>> TOPAS grid [X Y Z]=%s, resolution=%s mm\n', ...
    mat2str(topas_dims), mat2str(resolution_mm));
fprintf('>>> matRad sparse dimensions [Y X Z]=%s, voxels=%d\n', ...
    mat2str(dim_matRad), num_voxels);

scorer_dir = '';
for i = 1:numel(scorer_dir_candidates)
    if isfolder(scorer_dir_candidates{i})
        files = dir(fullfile(scorer_dir_candidates{i}, 'OSMK_Dtotal*_Run_*.bin'));
        if isempty(files)
            files = dir(fullfile(scorer_dir_candidates{i}, 'OSMK_Dtotal*_Run_*.csv'));
        end
        if ~isempty(files)
            scorer_dir = scorer_dir_candidates{i};
            break;
        end
    end
end

if isempty(scorer_dir)
    error(['No OSMK scorer .bin or .csv files found. Put the retrieved TOPAS files in ', ...
           'one of these folders or edit scorer_dir_candidates:\n%s'], ...
        strjoin(scorer_dir_candidates, newline));
end

sample_files = dir(fullfile(scorer_dir, 'OSMK_Dtotal*_Run_*.bin'));
if isempty(sample_files)
    sample_files = dir(fullfile(scorer_dir, 'OSMK_Dtotal*_Run_*.csv'));
end
verifyTopasScorerLayout(fullfile(sample_files(1).folder, sample_files(1).name), topas_dims);
topas_to_matrad_idx = makeTopasToMatRadIndex(topas_dims);

fprintf('>>> TOPAS OSMK scorer folder: %s\n', scorer_dir);
fprintf('>>> Output file: %s\n', output_file);
fprintf('>>> Spots: %d, voxels: %d, dimensions [Y X Z]=%s\n', ...
    num_spots, num_voxels, mat2str(dim_matRad));
fprintf('>>> TOPAS grid [X Y Z]=%s, resolution=%s mm\n', ...
    mat2str(topas_dims), mat2str(resolution_mm));
fprintf('>>> TOPAS spot grouping: %s\n', topas_spot_grouping);
fprintf('>>> TOPAS chunks from spots files: %d\n', num_topas_chunks);
fprintf('>>> Thresholds: dose=%g, zd=%g, zdstar=%g, zn=%g\n', ...
    dose_limit, zd_limit, zdstar_limit, zn_limit);

audit_weights = [];
if isfile(optimizer_result_file)
    optimizer_result = load(optimizer_result_file, 'resultGUI');
    if isfield(optimizer_result, 'resultGUI') && ...
            isfield(optimizer_result.resultGUI, 'w')
        audit_weights = double(optimizer_result.resultGUI.w(:));
        if numel(audit_weights) ~= num_spots
            warning(['Cannot audit Dtotal threshold with %s: resultGUI.w ', ...
                'has %d entries, expected %d spots.'], optimizer_result_file, ...
                numel(audit_weights), num_spots);
            audit_weights = [];
        elseif any(~isfinite(audit_weights))
            warning(['Cannot audit Dtotal threshold with %s: resultGUI.w ', ...
                'contains non-finite entries.'], optimizer_result_file);
            audit_weights = [];
        else
            fprintf('>>> Threshold audit weights: %s (sum(abs(w))=%.12g)\n', ...
                optimizer_result_file, sum(abs(audit_weights)));
            fprintf(['>>> Conservative accumulated Dtotal omission bound: ', ...
                'dose_limit * sum(abs(w)) = %.12g Gy/voxel\n'], ...
                dose_limit * sum(abs(audit_weights)));
        end
    end
end

%% Allocate per-chunk outputs
total_dose_chunks = cell(num_dij_chunks, 1);
weighted_zd_chunks = cell(num_dij_chunks, 1);
weighted_zd_star_chunks = cell(num_dij_chunks, 1);
weighted_zn_chunks = cell(num_dij_chunks, 1);
dij_chunk_spot_ids = cell(num_dij_chunks, 1);

total_dose_sum_by_spot = zeros(num_spots, 1);
weighted_zd_sum_by_spot = zeros(num_spots, 1);
weighted_zd_star_sum_by_spot = zeros(num_spots, 1);
weighted_zn_sum_by_spot = zeros(num_spots, 1);
total_dose_raw_sum_by_spot = zeros(num_spots, 1);
weighted_zd_raw_sum_by_spot = zeros(num_spots, 1);
weighted_zd_star_raw_sum_by_spot = zeros(num_spots, 1);
weighted_zn_raw_sum_by_spot = zeros(num_spots, 1);
total_dose_dropped_sum_by_spot = zeros(num_spots, 1);
weighted_zd_dropped_sum_by_spot = zeros(num_spots, 1);
weighted_zd_star_dropped_sum_by_spot = zeros(num_spots, 1);
weighted_zn_dropped_sum_by_spot = zeros(num_spots, 1);
total_dose_nnz_by_spot = zeros(num_spots, 1);
weighted_zd_nnz_by_spot = zeros(num_spots, 1);
weighted_zd_star_nnz_by_spot = zeros(num_spots, 1);
weighted_zn_nnz_by_spot = zeros(num_spots, 1);
total_dose_dropped_by_spot = zeros(num_spots, 1);
weighted_zd_dropped_by_spot = zeros(num_spots, 1);
weighted_zd_star_dropped_by_spot = zeros(num_spots, 1);
weighted_zn_dropped_by_spot = zeros(num_spots, 1);
missing_scorer_by_spot = cell(num_spots, 1);
bad_scorer_by_spot = cell(num_spots, 1);

%% Main per-spot build loop
pool = [];
if use_parallel && exist('gcp', 'file') == 2 && exist('parpool', 'file') == 2
    pool = gcp('nocreate');
    if isempty(pool)
        pool = parpool('local', num_workers);
    elseif pool.NumWorkers ~= num_workers
        fprintf('>>> Restarting existing parallel pool (%d workers) as %d workers...\n', ...
            pool.NumWorkers, num_workers);
        delete(pool);
        pool = parpool('local', num_workers);
    end
end

if isempty(pool)
    fprintf('>>> Building sparse OSMK matrices serially...\n');
else
    fprintf(['>>> Building sparse OSMK matrices with %d workers...\n', ...
        '    DIJ chunks are serial; spots inside each chunk are read/thresholded in parallel.\n'], ...
        pool.NumWorkers);
end
tic;

for dij_chunk = 1:num_dij_chunks
    first_work_ix = (dij_chunk - 1) * max_spots_per_dij_chunk + 1;
    last_work_ix = min(dij_chunk * max_spots_per_dij_chunk, numel(work_spot_ids));
    work_ix = first_work_ix:last_work_ix;

    topas_chunks_this_dij_chunk = work_topas_chunks(work_ix);
    run_ids_this_dij_chunk = work_run_ids(work_ix);
    spot_indices = work_spot_ids(work_ix);
    num_spots_in_chunk = numel(spot_indices);

    chunk_cols = cell(num_spots_in_chunk, 1);
    chunk_sums = zeros(num_spots_in_chunk, 4);
    chunk_raw_sums = zeros(num_spots_in_chunk, 4);
    chunk_dropped_sums = zeros(num_spots_in_chunk, 4);
    chunk_kept_nnz = zeros(num_spots_in_chunk, 4);
    chunk_dropped_nnz = zeros(num_spots_in_chunk, 4);
    chunk_missing = cell(num_spots_in_chunk, 1);
    chunk_bad = cell(num_spots_in_chunk, 1);

    if isempty(pool)
        for run_pos = 1:num_spots_in_chunk
            topas_chunk = topas_chunks_this_dij_chunk(run_pos);
            run_id = run_ids_this_dij_chunk(run_pos);
            spot_idx = spot_indices(run_pos);
            [cols, sums, raw_sums, dropped_sums, kept_nnz, dropped_nnz, missing, bad] = buildSparseSpotColumns( ...
                topas_chunk, run_id, scorer_dir, scorer_names, scorer_limits, preferred_scorer_extension, ...
                topas_to_matrad_idx, num_voxels, fail_on_missing);

            chunk_cols{run_pos} = cols;
            chunk_sums(run_pos, :) = sums(:)';
            chunk_raw_sums(run_pos, :) = raw_sums(:)';
            chunk_dropped_sums(run_pos, :) = dropped_sums(:)';
            chunk_kept_nnz(run_pos, :) = kept_nnz(:)';
            chunk_dropped_nnz(run_pos, :) = dropped_nnz(:)';
            chunk_missing{run_pos} = missing;
            chunk_bad{run_pos} = bad;
        end
    else
        parfor run_pos = 1:num_spots_in_chunk
            topas_chunk = topas_chunks_this_dij_chunk(run_pos);
            run_id = run_ids_this_dij_chunk(run_pos);
            spot_idx = spot_indices(run_pos);
            [cols, sums, raw_sums, dropped_sums, kept_nnz, dropped_nnz, missing, bad] = buildSparseSpotColumns( ...
                topas_chunk, run_id, scorer_dir, scorer_names, scorer_limits, preferred_scorer_extension, ...
                topas_to_matrad_idx, num_voxels, fail_on_missing);

            chunk_cols{run_pos} = cols;
            chunk_sums(run_pos, :) = sums(:)';
            chunk_raw_sums(run_pos, :) = raw_sums(:)';
            chunk_dropped_sums(run_pos, :) = dropped_sums(:)';
            chunk_kept_nnz(run_pos, :) = kept_nnz(:)';
            chunk_dropped_nnz(run_pos, :) = dropped_nnz(:)';
            chunk_missing{run_pos} = missing;
            chunk_bad{run_pos} = bad;
        end
    end

    total_dose_local = cell(1, num_spots_in_chunk);
    weighted_zd_local = cell(1, num_spots_in_chunk);
    weighted_zd_star_local = cell(1, num_spots_in_chunk);
    weighted_zn_local = cell(1, num_spots_in_chunk);

    for run_pos = 1:num_spots_in_chunk
        spot_idx = spot_indices(run_pos);
        cols = chunk_cols{run_pos};
        sums = chunk_sums(run_pos, :)';
        raw_sums = chunk_raw_sums(run_pos, :)';
        dropped_sums = chunk_dropped_sums(run_pos, :)';
        kept_nnz = chunk_kept_nnz(run_pos, :)';
        dropped_nnz = chunk_dropped_nnz(run_pos, :)';
        missing = chunk_missing{run_pos};
        bad = chunk_bad{run_pos};

        if isempty(bad)
            total_dose_sum_by_spot(spot_idx) = sums(1);
            weighted_zd_sum_by_spot(spot_idx) = sums(2);
            weighted_zd_star_sum_by_spot(spot_idx) = sums(3);
            weighted_zn_sum_by_spot(spot_idx) = sums(4);
            total_dose_raw_sum_by_spot(spot_idx) = raw_sums(1);
            weighted_zd_raw_sum_by_spot(spot_idx) = raw_sums(2);
            weighted_zd_star_raw_sum_by_spot(spot_idx) = raw_sums(3);
            weighted_zn_raw_sum_by_spot(spot_idx) = raw_sums(4);
            total_dose_dropped_sum_by_spot(spot_idx) = dropped_sums(1);
            weighted_zd_dropped_sum_by_spot(spot_idx) = dropped_sums(2);
            weighted_zd_star_dropped_sum_by_spot(spot_idx) = dropped_sums(3);
            weighted_zn_dropped_sum_by_spot(spot_idx) = dropped_sums(4);
            total_dose_nnz_by_spot(spot_idx) = kept_nnz(1);
            weighted_zd_nnz_by_spot(spot_idx) = kept_nnz(2);
            weighted_zd_star_nnz_by_spot(spot_idx) = kept_nnz(3);
            weighted_zn_nnz_by_spot(spot_idx) = kept_nnz(4);
            total_dose_dropped_by_spot(spot_idx) = dropped_nnz(1);
            weighted_zd_dropped_by_spot(spot_idx) = dropped_nnz(2);
            weighted_zd_star_dropped_by_spot(spot_idx) = dropped_nnz(3);
            weighted_zn_dropped_by_spot(spot_idx) = dropped_nnz(4);
        end

        total_dose_local{run_pos} = cols{1};
        weighted_zd_local{run_pos} = cols{2};
        weighted_zd_star_local{run_pos} = cols{3};
        weighted_zn_local{run_pos} = cols{4};

        missing_scorer_by_spot{spot_idx} = missing;
        bad_scorer_by_spot{spot_idx} = bad;
    end

    total_dose_chunks{dij_chunk} = [total_dose_local{:}];
    weighted_zd_chunks{dij_chunk} = [weighted_zd_local{:}];
    weighted_zd_star_chunks{dij_chunk} = [weighted_zd_star_local{:}];
    weighted_zn_chunks{dij_chunk} = [weighted_zn_local{:}];
    dij_chunk_spot_ids{dij_chunk} = spot_indices(:);

    fprintf('  Processed DIJ chunk %d / %d (%d spots, global spot %d to %d)\n', ...
        dij_chunk, num_dij_chunks, num_spots_in_chunk, spot_indices(1), spot_indices(end));
end

elapsed_sec = toc;
fprintf('>>> Finished reading TOPAS scorer files in %.1f s\n', elapsed_sec);

raw_dose_sum = sum(total_dose_raw_sum_by_spot);
dropped_dose_sum = sum(total_dose_dropped_sum_by_spot);
fprintf('>>> Dtotal raw/kept/dropped sums: %.12g / %.12g / %.12g Gy-voxel\n', ...
    raw_dose_sum, sum(total_dose_sum_by_spot), dropped_dose_sum);
fprintf('>>> Dtotal dropped fraction: %.6g%%\n', ...
    100 * dropped_dose_sum / max(raw_dose_sum, realmin));
if dropped_dose_sum / max(raw_dose_sum, realmin) > 1e-3
    warning(['Dtotal sparsification discarded more than 0.1%% of the raw ', ...
        'integral. Check the optimized-weighted dropped sum before using ', ...
        'this Dij for strict dose or sub-millimetre gamma validation.']);
end

if ~isempty(audit_weights)
    weighted_kept_integral = dot(total_dose_sum_by_spot, audit_weights);
    weighted_dropped_integral = dot(total_dose_dropped_sum_by_spot, audit_weights);
    weighted_raw_integral = weighted_kept_integral + weighted_dropped_integral;
    fprintf(['>>> Optimized-plan Dtotal kept/dropped/raw integrals: ', ...
        '%.12g / %.12g / %.12g Gy-voxel\n'], weighted_kept_integral, ...
        weighted_dropped_integral, weighted_raw_integral);
    fprintf('>>> Optimized-plan Dtotal integral loss: %.6g%%\n', ...
        100 * weighted_dropped_integral / max(abs(weighted_raw_integral), realmin));
end

fprintf('>>> Merging %d DIJ chunks into final sparse matrices...\n', num_dij_chunks);
merged_spot_ids = vertcat(dij_chunk_spot_ids{:});
if isequal(merged_spot_ids(:), (1:num_spots)')
    total_dose_sparse = [total_dose_chunks{:}];
    weighted_zd_sparse = [weighted_zd_chunks{:}];
    weighted_zd_star_sparse = [weighted_zd_star_chunks{:}];
    weighted_zn_sparse = [weighted_zn_chunks{:}];
else
    warning(['DIJ chunk spot IDs are not already in 1..N order. Merging ', ...
        'with one final column reorder.']);
    [~, col_order] = sort(merged_spot_ids);
    total_dose_sparse = [total_dose_chunks{:}];
    weighted_zd_sparse = [weighted_zd_chunks{:}];
    weighted_zd_star_sparse = [weighted_zd_star_chunks{:}];
    weighted_zn_sparse = [weighted_zn_chunks{:}];
    total_dose_sparse = total_dose_sparse(:, col_order);
    weighted_zd_sparse = weighted_zd_sparse(:, col_order);
    weighted_zd_star_sparse = weighted_zd_star_sparse(:, col_order);
    weighted_zn_sparse = weighted_zn_sparse(:, col_order);
end

missing_scorer_files = flattenStringCells(missing_scorer_by_spot);
bad_scorer_files = flattenStringCells(bad_scorer_by_spot);

if ~isempty(missing_scorer_files)
    warning(['%d OSMK scorer files are missing. Missing spots were saved as ', ...
        'zero columns. Do not use this bioDij for final optimization until ', ...
        'missingScorerFiles is empty.'], numel(missing_scorer_files));
end
if ~isempty(bad_scorer_files)
    warning(['%d OSMK scorer files could not be read. Bad spots were saved ', ...
        'as zero columns.'], numel(bad_scorer_files));
end

%% Save
bioDij = struct();
bioDij.totalDose = total_dose_sparse;
bioDij.weighted_zd = weighted_zd_sparse;
bioDij.weighted_zd_star = weighted_zd_star_sparse;
bioDij.weighted_zn = weighted_zn_sparse;

bioDij.bixelNum = num_spots;
bioDij.numOfBeams = 1;
bioDij.dimensions = dim_matRad;
bioDij.topasDimensions = topas_dims;
bioDij.resolution = resolution_mm;
bioDij.dicomCropInfo = dicom_crop_info;
bioDij.storageClass = 'sparse double';
bioDij.ionLabel = ion_label;
bioDij.flipOpposingBeamY = false;
bioDij.flipYBySpot = false(num_spots, 1);
bioDij.flipYNumSpots = 0;
bioDij.shiftOpposingBeamTopasX = false;
bioDij.opposingBeamTopasXShiftMm = 0;
bioDij.opposingBeamTopasXShiftBins = 0;
bioDij.thresholds = struct('dose', dose_limit, 'zd', zd_limit, ...
    'zdstar', zdstar_limit, 'zn', zn_limit);
bioDij.thresholdAuditOptimizerResultFile = optimizer_result_file;
bioDij.thresholdAuditWeightSumAbs = sum(abs(audit_weights));
bioDij.thresholdAuditDosePerVoxelUpperBoundGy = ...
    dose_limit * sum(abs(audit_weights));
bioDij.scorerNames = scorer_names;
bioDij.scorerDir = scorer_dir;
bioDij.preferredScorerExtension = preferred_scorer_extension;
bioDij.topasSpotGrouping = topas_spot_grouping;
bioDij.topasSpotGroups = topas_spot_groups;
bioDij.spotsDir = spots_dir;
bioDij.maxSpotsPerDijChunk = max_spots_per_dij_chunk;
bioDij.numDijChunks = num_dij_chunks;
bioDij.dijChunkSpotIds = dij_chunk_spot_ids;
bioDij.totalDoseSumBySpot = total_dose_sum_by_spot;
bioDij.weightedZdSumBySpot = weighted_zd_sum_by_spot;
bioDij.weightedZdStarSumBySpot = weighted_zd_star_sum_by_spot;
bioDij.weightedZnSumBySpot = weighted_zn_sum_by_spot;
bioDij.totalDoseRawSumBySpot = total_dose_raw_sum_by_spot;
bioDij.weightedZdRawSumBySpot = weighted_zd_raw_sum_by_spot;
bioDij.weightedZdStarRawSumBySpot = weighted_zd_star_raw_sum_by_spot;
bioDij.weightedZnRawSumBySpot = weighted_zn_raw_sum_by_spot;
bioDij.totalDoseDroppedSumBySpot = total_dose_dropped_sum_by_spot;
bioDij.weightedZdDroppedSumBySpot = weighted_zd_dropped_sum_by_spot;
bioDij.weightedZdStarDroppedSumBySpot = weighted_zd_star_dropped_sum_by_spot;
bioDij.weightedZnDroppedSumBySpot = weighted_zn_dropped_sum_by_spot;
bioDij.totalDoseNnzBySpot = total_dose_nnz_by_spot;
bioDij.weightedZdNnzBySpot = weighted_zd_nnz_by_spot;
bioDij.weightedZdStarNnzBySpot = weighted_zd_star_nnz_by_spot;
bioDij.weightedZnNnzBySpot = weighted_zn_nnz_by_spot;
bioDij.totalDoseDroppedBySpot = total_dose_dropped_by_spot;
bioDij.weightedZdDroppedBySpot = weighted_zd_dropped_by_spot;
bioDij.weightedZdStarDroppedBySpot = weighted_zd_star_dropped_by_spot;
bioDij.weightedZnDroppedBySpot = weighted_zn_dropped_by_spot;
bioDij.missingScorerFiles = missing_scorer_files;
bioDij.badScorerFiles = bad_scorer_files;
bioDij.photonElectronDoseAvailable = false;
bioDij.createdBy = mfilename;
bioDij.createdOn = char(datetime('now'));
bioDij.description = ['Sparse-double OSMK direct scorer DIJ. Entries below ', ...
    'the configured thresholds are stored as zero. Divide weighted_* * x ', ...
    'by totalDose * x in the RBE code. Scorers are attached to TOPAS ', ...
    'Component="Patient"; importer maps TOPAS [X Y Z] voxel order to ', ...
    'matRad [Y X Z] and uses spots files to map chunk/run indices back ', ...
    'to global spot columns.'];

fprintf('>>> Saving %s ...\n', output_file);
save(output_file, 'bioDij', '-v7.3');

fprintf('>>> Saved sparse bioDij.\n');
fprintf('    totalDose nnz        : %d\n', nnz(bioDij.totalDose));
fprintf('    weighted_zd nnz      : %d\n', nnz(bioDij.weighted_zd));
fprintf('    weighted_zd_star nnz : %d\n', nnz(bioDij.weighted_zd_star));
fprintf('    weighted_zn nnz      : %d\n', nnz(bioDij.weighted_zn));
fprintf('    missing scorer files : %d\n', numel(missing_scorer_files));
fprintf('    bad scorer files     : %d\n', numel(bad_scorer_files));

%% Local functions
function [topas_dims, resolution_mm, dicomCropInfo] = getCurrentTopasGrid(project_dir)
dicom_info_file = fullfile(project_dir, 'dicom', 'dicomCropInfo.mat');
if ~isfile(dicom_info_file)
    error('Missing DICOM crop info: %s. Run crop_dicom_for_topas first.', dicom_info_file);
end

s = load(dicom_info_file, 'dicomCropInfo');
dicomCropInfo = s.dicomCropInfo;

required_fields = {'outputColumnsRowsSlices', 'pixelSpacingRowColMm', 'sliceSpacingMm'};
for f = 1:numel(required_fields)
    if ~isfield(dicomCropInfo, required_fields{f})
        error('dicomCropInfo.%s is missing in %s.', required_fields{f}, dicom_info_file);
    end
end

topas_dims = double(dicomCropInfo.outputColumnsRowsSlices(:).');
resolution_mm = [ ...
    double(dicomCropInfo.pixelSpacingRowColMm(2)), ...
    double(dicomCropInfo.pixelSpacingRowColMm(1)), ...
    double(dicomCropInfo.sliceSpacingMm)];

if numel(topas_dims) ~= 3 || any(~isfinite(topas_dims)) || any(topas_dims <= 0) || any(topas_dims ~= round(topas_dims))
    error('Invalid TOPAS dimensions in dicomCropInfo: %s.', mat2str(topas_dims));
end
if any(~isfinite(resolution_mm)) || any(resolution_mm <= 0)
    error('Invalid TOPAS resolution in dicomCropInfo: %s.', mat2str(resolution_mm));
end
end

function tf = defaultUseParallel()
% Current 0.5 x 0.5 x 2 mm scorer files are large; serial import is safer.
tf = false;
end

function spot_groups = readTopasSpotGroupsFromSpotsFiles(spots_dir, ion_label)
if ~isfolder(spots_dir)
    error('Missing TOPAS scripts folder: %s.', spots_dir);
end

files = dir(fullfile(spots_dir, sprintf('spots_%s_*.txt', ion_label)));
if isempty(files)
    error('No spots_%s_*.txt files found in %s.', ion_label, spots_dir);
end

chunk_ids = nan(numel(files), 1);
for i = 1:numel(files)
    token = regexp(files(i).name, sprintf('^spots_%s_(\\d+)\\.txt$', ion_label), 'tokens', 'once');
    if isempty(token)
        continue;
    end
    chunk_ids(i) = str2double(token{1});
end

valid = isfinite(chunk_ids);
files = files(valid);
chunk_ids = chunk_ids(valid);
if isempty(files)
    error('No numbered spots_%s_XX.txt files found in %s.', ion_label, spots_dir);
end

[chunk_ids, order] = sort(chunk_ids);
files = files(order);
if ~isequal(chunk_ids(:), (1:numel(chunk_ids))')
    error('Chunk IDs for spots_%s_*.txt are not contiguous starting at 1: %s.', ...
        ion_label, mat2str(chunk_ids(:).'));
end

spot_groups = cell(numel(files), 1);
for i = 1:numel(files)
    spot_groups{i} = parseGlobalSpotIdsFromSpotsFile(fullfile(files(i).folder, files(i).name));
end
end

function spot_ids = parseGlobalSpotIdsFromSpotsFile(spots_file)
text = fileread(spots_file);
token = regexp(text, 'iv:Tf/Scatterer1/L0/Values\s*=\s*(\d+)\s+([^\r\n]+)', 'tokens', 'once');
if isempty(token)
    error('Could not find global spot ID line iv:Tf/Scatterer1/L0/Values in %s.', spots_file);
end

declared_count = str2double(token{1});
spot_ids = sscanf(token{2}, '%f').';
if numel(spot_ids) ~= declared_count
    error('Spot count mismatch in %s: declared %d IDs, parsed %d.', ...
        spots_file, declared_count, numel(spot_ids));
end
if any(~isfinite(spot_ids)) || any(spot_ids ~= round(spot_ids)) || any(spot_ids <= 0)
    error('Invalid global spot IDs in %s.', spots_file);
end
spot_ids = double(spot_ids(:));
end

function [topas_chunks, run_ids, spot_ids] = makeSpotWorkItems(topas_spot_groups)
    num_spots = sum(cellfun(@numel, topas_spot_groups));
    topas_chunks = zeros(num_spots, 1);
    run_ids = zeros(num_spots, 1);
    spot_ids = zeros(num_spots, 1);

    next_ix = 1;
    for chunk = 1:numel(topas_spot_groups)
        ids = topas_spot_groups{chunk}(:);
        n = numel(ids);
        ix = next_ix:(next_ix + n - 1);
        topas_chunks(ix) = chunk;
        run_ids(ix) = (0:(n - 1)).';
        spot_ids(ix) = ids;
        next_ix = next_ix + n;
    end
end

function [cols, sums, raw_sums, dropped_sums, kept_nnz, dropped_nnz, missing, bad] = buildSparseSpotColumns( ...
    chunk, run_id, scorer_dir, scorer_names, scorer_limits, preferred_scorer_extension, ...
    topas_to_matrad_idx, num_voxels, fail_on_missing)

    cols = {
        sparse(num_voxels, 1)
        sparse(num_voxels, 1)
        sparse(num_voxels, 1)
        sparse(num_voxels, 1)
        };
    sums = zeros(4, 1);
    raw_sums = zeros(4, 1);
    dropped_sums = zeros(4, 1);
    kept_nnz = zeros(4, 1);
    dropped_nnz = zeros(4, 1);
    missing = strings(0, 1);
    bad = strings(0, 1);

    files = cell(numel(scorer_names), 1);
    for i = 1:numel(scorer_names)
        files{i} = resolveTopasScorerFile(scorer_dir, scorer_names{i}, ...
            chunk, run_id, preferred_scorer_extension);
        if ~isfile(files{i})
            missing(end+1, 1) = string(files{i}); %#ok<AGROW>
        end
    end

    if ~isempty(missing)
        if fail_on_missing
            error('Missing required OSMK scorer file for chunk %d run %04d: %s', ...
                chunk, run_id, missing(1));
        end
        return;
    end

    for i = 1:numel(scorer_names)
        try
            [cols{i}, sums(i), raw_sums(i), dropped_sums(i), kept_nnz(i), dropped_nnz(i)] = ...
                readThresholdedSparseColumn(files{i}, topas_to_matrad_idx, ...
                    scorer_limits(i), num_voxels);
        catch ME
            if fail_on_missing
                rethrow(ME);
            end
            warning('Failed to read %s: %s', files{i}, ME.message);
            bad = string(files(:));
            cols = {
                sparse(num_voxels, 1)
                sparse(num_voxels, 1)
                sparse(num_voxels, 1)
                sparse(num_voxels, 1)
                };
            sums(:) = 0;
            raw_sums(:) = 0;
            dropped_sums(:) = 0;
            kept_nnz(:) = 0;
            dropped_nnz(:) = 0;
            return;
        end
    end
end

function filename = resolveTopasScorerFile(scorer_dir, scorer_name, chunk, run_id, preferred_ext)
    extensions = unique([{preferred_ext}, {'.bin'}, {'.csv'}], 'stable');

    for extIx = 1:numel(extensions)
        ext = extensions{extIx};
        exact_names = {
            fullfile(scorer_dir, sprintf('%s_%02d_Run_%04d%s', scorer_name, chunk, run_id, ext))
            };

        for exactIx = 1:numel(exact_names)
            if isfile(exact_names{exactIx})
                filename = exact_names{exactIx};
                return;
            end
        end

        labelled = dir(fullfile(scorer_dir, ...
            sprintf('%s_*_%02d_Run_%04d%s', scorer_name, chunk, run_id, ext)));
        if ~isempty(labelled)
            [~, order] = sort({labelled.name});
            labelled = labelled(order);
            filename = fullfile(labelled(1).folder, labelled(1).name);
            return;
        end
    end

    filename = fullfile(scorer_dir, sprintf('%s_*_%02d_Run_%04d%s', ...
        scorer_name, chunk, run_id, preferred_ext));
end

function [col_sparse, kept_sum, raw_sum, dropped_sum, kept_nnz, dropped_nnz] = readThresholdedSparseColumn( ...
    filename, topas_to_matrad_idx, value_limit, num_voxels)

    values = readTopasScorerValues(filename, num_voxels);
    finite_mask = isfinite(values);
    nonzero_mask = finite_mask & values ~= 0;
    keep_mask = nonzero_mask & abs(values) >= value_limit;

    matrad_rows = double(topas_to_matrad_idx(keep_mask));
    kept_values = values(keep_mask);
    raw_sum = sum(values(nonzero_mask));

    col_sparse = sparse(matrad_rows, ones(numel(matrad_rows), 1), ...
        kept_values, num_voxels, 1);
    kept_sum = sum(kept_values);
    dropped_sum = raw_sum - kept_sum;
    kept_nnz = numel(kept_values);
    dropped_nnz = nnz(nonzero_mask) - kept_nnz;
end

function values = readTopasScorerValues(filename, expected_rows)
    [~, ~, ext] = fileparts(filename);
    switch lower(ext)
        case '.bin'
            values = readTopasBinaryValues(filename, expected_rows);
        case '.csv'
            values = readTopasCsvValues(filename, expected_rows);
        otherwise
            error('Unsupported TOPAS scorer file extension in %s.', filename);
    end
end

function values = readTopasBinaryValues(filename, expected_rows)
    fid = fopen(filename, 'rb');
    if fid == -1
        error('Cannot open TOPAS binary file: %s', filename);
    end
    cleaner = onCleanup(@() fclose(fid));

    values = fread(fid, expected_rows, 'double=>double');
    if numel(values) ~= expected_rows
        error('Binary value count mismatch in %s: got %d, expected %d.', ...
            filename, numel(values), expected_rows);
    end
end

function values = readTopasCsvValues(filename, expected_rows)
    fid = fopen(filename, 'r');
    if fid == -1
        error('Cannot open TOPAS CSV file: %s', filename);
    end
    cleaner = onCleanup(@() fclose(fid));

    data = textscan(fid, '%*f%*f%*f%f', 'Delimiter', ',', ...
        'CommentStyle', '#');
    values = data{1};

    if isempty(values)
        error('Empty TOPAS CSV file: %s', filename);
    end
    if numel(values) ~= expected_rows
        error('Row count mismatch in %s: got %d, expected %d.', ...
            filename, numel(values), expected_rows);
    end
end

function verifyTopasScorerLayout(filename, topas_dims)
    [~, ~, ext] = fileparts(filename);
    switch lower(ext)
        case '.bin'
            verifyTopasBinaryLayout(filename, topas_dims);
        case '.csv'
            verifyTopasCsvIndexOrder(filename, topas_dims);
        otherwise
            error('Unsupported TOPAS scorer file extension in %s.', filename);
    end
end

function verifyTopasBinaryLayout(filename, topas_dims)
    expected_bytes = prod(topas_dims) * 8;
    file_info = dir(filename);
    if isempty(file_info)
        error('Cannot find TOPAS binary file for layout verification: %s', filename);
    end
    if file_info.bytes ~= expected_bytes
        error('Binary size mismatch in %s: got %d bytes, expected %d.', ...
            filename, file_info.bytes, expected_bytes);
    end

    header_file = [filename 'header'];
    if isfile(header_file)
        verifyTopasBinaryHeader(header_file, topas_dims);
    end
end

function verifyTopasBinaryHeader(header_file, topas_dims)
    text = fileread(header_file);
    axes = 'XYZ';
    for axisIx = 1:numel(axes)
        pattern = sprintf('#\\s*%s\\s+in\\s+(\\d+)\\s+bins?', axes(axisIx));
        token = regexp(text, pattern, 'tokens', 'once');
        if isempty(token)
            error('Could not parse %s-axis binning from %s.', axes(axisIx), header_file);
        end
        n_bins = str2double(token{1});
        if n_bins ~= topas_dims(axisIx)
            error('%s-axis bin mismatch in %s: got %d, expected %d.', ...
                axes(axisIx), header_file, n_bins, topas_dims(axisIx));
        end
    end
end

function verifyTopasCsvIndexOrder(filename, topas_dims)
    fid = fopen(filename, 'r');
    if fid == -1
        error('Cannot open TOPAS CSV file for index verification: %s', filename);
    end
    cleaner = onCleanup(@() fclose(fid));

    data = textscan(fid, '%f%f%f%*f', 'Delimiter', ',', ...
        'CommentStyle', '#', 'CollectOutput', true);
    raw = data{1};
    expected_rows = prod(topas_dims);

    if size(raw, 1) ~= expected_rows
        error('Row count mismatch in %s: got %d, expected %d.', ...
            filename, size(raw, 1), expected_rows);
    end

    x = raw(:, 1);
    y = raw(:, 2);
    z = raw(:, 3);
    if any(x < 0 | y < 0 | z < 0 | ...
           x >= topas_dims(1) | y >= topas_dims(2) | z >= topas_dims(3) | ...
           x ~= floor(x) | y ~= floor(y) | z ~= floor(z))
        error('Invalid TOPAS voxel indices in %s.', filename);
    end

    linear_idx = x + y .* topas_dims(1) + z .* topas_dims(1) .* topas_dims(2);
    expected_idx = (0:(expected_rows - 1))';
    if any(linear_idx ~= expected_idx)
        error(['Unexpected TOPAS CSV voxel order in %s. This sparse builder ', ...
            'expects standard TOPAS order with X changing fastest.'], filename);
    end
end

function topas_to_matrad_idx = makeTopasToMatRadIndex(topas_dims, flip_y)
    if nargin < 2
        flip_y = false;
    end

    num_voxels = prod(topas_dims);
    topas_linear = reshape(uint32(1:num_voxels), topas_dims);
    if flip_y
        topas_linear = topas_linear(:, end:-1:1, :);
    end
    topas_idx_in_matrad_order = permute(topas_linear, [2, 1, 3]);
    topas_to_matrad_idx = zeros(num_voxels, 1, 'uint32');
    topas_to_matrad_idx(topas_idx_in_matrad_order(:)) = uint32(1:num_voxels);
end

function out = flattenStringCells(cells_in)
    out = strings(0, 1);
    for i = 1:numel(cells_in)
        if ~isempty(cells_in{i})
            out = [out; string(cells_in{i}(:))]; %#ok<AGROW>
        end
    end
end
